/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author 182210014
 */
public class MenuPrincipal extends javax.swing.JFrame implements InternalFrameListener{

    /**
     * Creates new form MenuPrincipal
     */
    
    private boolean flagGUICadLivro = false;
    private boolean flagGUIManuLivro = false;
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jdpAreaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastrar = new javax.swing.JMenu();
        jmiCadastrarLivro = new javax.swing.JMenuItem();
        jmLivro = new javax.swing.JMenu();
        jmiLivros = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpAreaTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaTrabalho);
        jdpAreaTrabalho.setLayout(jdpAreaTrabalhoLayout);
        jdpAreaTrabalhoLayout.setHorizontalGroup(
            jdpAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jdpAreaTrabalhoLayout.setVerticalGroup(
            jdpAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jmCadastrar.setText("Cadastrar");

        jmiCadastrarLivro.setText("Cadastrar Livro");
        jmiCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarLivroActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiCadastrarLivro);

        jMenuBar1.add(jmCadastrar);

        jmLivro.setText("Livro");
        jmLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLivroActionPerformed(evt);
            }
        });

        jmiLivros.setText("Livros");
        jmiLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLivrosActionPerformed(evt);
            }
        });
        jmLivro.add(jmiLivros);

        jMenuBar1.add(jmLivro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaTrabalho)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarLivro(){
        if(!flagGUICadLivro){
            GUICadLivro gcl = new GUICadLivro();
            jdpAreaTrabalho.add(gcl);
            gcl.setVisible(true);
            
            flagGUICadLivro = true;
            gcl.addInternalFrameListener(this);
        }
    } 
    
    private void abrirLivro(){
        if(!flagGUIManuLivro){
            GUIManuLivro gml = new GUIManuLivro();
            jdpAreaTrabalho.add(gml);
            gml.setVisible(true); 
            flagGUIManuLivro = true; 
            gml.addInternalFrameListener(this);
        }
        
    }
    
    private void jmiCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarLivroActionPerformed
        cadastrarLivro();
    }//GEN-LAST:event_jmiCadastrarLivroActionPerformed

    private void jmLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLivroActionPerformed
       
    }//GEN-LAST:event_jmLivroActionPerformed

    private void jmiLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLivrosActionPerformed
      abrirLivro();
    }//GEN-LAST:event_jmiLivrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdpAreaTrabalho;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmLivro;
    private javax.swing.JMenuItem jmiCadastrarLivro;
    private javax.swing.JMenuItem jmiLivros;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        if(ife.getInternalFrame() instanceof GUICadLivro){
            flagGUICadLivro = false;
        }else if (ife.getInternalFrame() instanceof GUIManuLivro){
            flagGUIManuLivro = false;
        }//fim do else
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {
       
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {
       
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {
        
    }
}
